<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSIoyiRz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSIoyiRz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSIoyiRz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSIoyiRz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSIoyiRz\App_KernelDevDebugContainer([
    'container.build_hash' => 'SIoyiRz',
    'container.build_id' => '4eac643a',
    'container.build_time' => 1697205164,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSIoyiRz');
